export const JWT_CLAIMS = {
	iat: "Issued At - When the token was created",
	exp: "Expires At - When the token expires",
	sub: "Subject - The user this token represents",
	aud: "Audience - Who this token is intended for",
	iss: "Issuer - Who created this token",
	nbf: "Not Before - Token is not valid before this time",
	jti: "JWT ID - Unique identifier for this token",
	name: "Full Name - The user's display name",
	email: "Email Address - The user's email",
	sessionToken: "Session Token - NextAuth session identifier",
	userId: "User ID - Unique user identifier",
	picture: "Profile Picture - URL to user's avatar",
	given_name: "First Name - User's given name",
	family_name: "Last Name - User's family name",
	locale: "Locale - User's preferred language/region",
	role: "Role - User's permission level",
	scope: "Scope - What this token can access",
} as const;
